Add types to fix compilation error when using compiler flag -Xsource:3
Compiler error message:

/home/runner/work/graalnative4s/graalnative4s/src/main/scala/app/Api.scala:56:23: under -Xsource:3, inferred List[sttp.tapir.server.ServerEndpoint[Any,F]] instead of List[sttp.tapir.server.ServerEndpoint[Any,F]{type OUTPUT >: String with this.Info <: java.io.Serializable; type ERROR_OUTPUT <: sttp.model.StatusCode; type INPUT >: Option[eu.timepit.refined.api.Refined[String,eu.timepit.refined.boolean.Not[eu.timepit.refined.collection.Empty]]] with Unit; type PRINCIPAL <: Unit; type SECURITY_INPUT <: Unit}]